spring:
  application:
    name: poc-request-api
  kafka:
    producer:
      acks: -1
#      bootstrap-servers: localhost:29092 quando executada em localhost e não dockerizada
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      pocQuoteRequest: poc-quote-request
      pocQuoteCalc: poc-quote-calc

server:
  port: 8081
  servlet:
    context-path: /poc-request-api

logging:
  level:
    root: INFO